version:  '3.7'
services:
  postgresql:
    image: postgres:12.2
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdbtest
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:4.22
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
        - 5050:80